version: '3'

services:
  chain1:
    image: issac/gleiphir
    hostname: chain1
    environment:
      GLEIPHIR_ID: chain1
      GLEIPHIR_SERVERS: chain1=0.0.0.0:7888 chain2=chain2:7888 chain3=chain3:7888

  chain2:
    image: issac/gleiphir
    hostname: chain2
    environment:
      GLEIPHIR_ID: chain2
      GLEIPHIR_SERVERS: chain1=chain1:7888 chain2=0.0.0.0:7888 chain3=chain3:7888

  chain3:
    image: issac/gleiphir
    hostname: chain3
    environment:
      GLEIPHIR_ID: chain3
      GLEIPHIR_SERVERS: chain1=chain1:7888 chain2=chain2:7888 chain3=0.0.0.0:7888
