version: '3'

services:
  node1:
    image: issac/gleiphir
    hostname: node1
    environment:
      GLEIPHIR_ID: node1
      GLEIPHIR_SERVERS: node1=localhost:7888 node2=node2:7888 node3=node3:7888

  node2:
    image: issac/gleiphir
    hostname: node2
    environment:
      GLEIPHIR_ID: node2
      GLEIPHIR_SERVERS: node1=node1:7888 node2=localhost:7888 node3=node3:7888

  node3:
    image: issac/gleiphir
    hostname: node3
    environment:
      GLEIPHIR_ID: node3
      GLEIPHIR_SERVERS: node1=node1:7888 node2=node2:7888 node3=localhost:7888
