#!/usr/bin/env bash

if [ ! -f install ]; then
echo 'install must be run within its container folder' 1>&2
exit 1
fi

CURDIR=`pwd`
export GOPATH="$CURDIR"

gofmt -w src

cd src && glide install
cd ..

docker build -t issac/gleiphir .